---
- name: Create link
  file: src=/home/vagrant/hushfile/hushfile-web
        dest=/var/www/hushfile-web
        state=link

- name: Create configuration file
  template:
    src: web-config.json
    dest: /var/www/hushfile-web/config.json  
