---
- name: Ensure requirements pip packages
  pip: requirements=/home/vagrant/hushfile/hushfile-py-server/requirements.txt

- name: Ensure data directory
  file:
    name: /data/hushfile-py-server
    state: directory
    owner: vagrant

- name: Write config file
  template: src=server-config.json
            dest=/home/vagrant/hushfile/hushfile-py-server/config.json
