---
- name: Ensure directories
  file: path={{ item }} state=directory
  with_items:
    - /data
    - /var/www
- name: Ensure basic packages
  apt: name={{ item }}
       update_cache=yes
       state=installed
  with_items:
    - git
    - vim
    - python
    - python-pip
- include: hushfile-py-server.yml
- include: hushfile-web.yml
- include: nginx.yml
