---
- name: Ensure packages
  apt: 
    name: nginx
    state: installed
    update-cache: yes

- name: Setup template
  template: 
    src: nginx.conf.j2
    dest: /etc/nginx/sites-enabled/hushfile
  notify: 
    - restart nginx

- name: Ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: yes
